### ISSUE TITLE
TypeError: Cannot read property 'createSnapshot' of undefined

### ISSUE THREAD

**Issue by veeramarni** [amaurymartiny/cra-lerna-electron#181]
Ran following commands, and it fails.

```
yarn install
yarn build
```

Errros
---
erna info Executing command in 2 packages: "yarn run build"
crale-react: $ react-scripts build
crale-react: The following changes are being made to your tsconfig.json file:
crale-react:   - compilerOptions.noFallthroughCasesInSwitch to be suggested value: true (this can be changed)
crale-react:   - compilerOptions.jsx must be react-jsx (to support the new JSX transform in React 17)
crale-react: Creating an optimized production build...
crale-react: /users/projects/examples/cra-lerna-electron/node_modules/react-scripts/scripts/build.js:19
crale-react:   throw err;
crale-react:   ^
crale-react: TypeError: Cannot read property 'createSnapshot' of undefined
crale-react:     at /users/projects/examples/cra-lerna-electron/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13:36
crale-react:     at new Promise (<anonymous>)
crale-react:     at Object.createSnapshot (/users/projects/examples/cra-lerna-electron/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:12:10)
crale-react:     at /users/projects/examples/cra-lerna-electron/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:219:35
crale-react: error Command failed with exit code 1.
crale-react: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by veeramarni** [comment]
I have changed webpack version in `crale-electron/package.json` to make it work. 

```
"webpack": "4.44.2"
```
